@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mustapelto.deepmoblearning.common.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;